test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: RottenTomatoes_test
  pool: 5
  username: root
  password:
  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: RottenTomatoes_development
  pool: 5
  username: root
  password:
  host: localhost