# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#

if Movie.count == 0
  Movie.create(title: 'Movie 1', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 2', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 3', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 4', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 5', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 6', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 7', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 8', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 9', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 10', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 11', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 12', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 13', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 14', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 15', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 16', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 17', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 18', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 19', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 20', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 21', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 22', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 23', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 24', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
  Movie.create(title: 'Movie 25', poster_thumb_url: 'http://content8.flixster.com/movie/11/16/39/11163966_tmb.jpg', year: 2011, mpaa_rating: 'PG-13', critics_rating: 'Certified Fresh', critics_score: 97, audience_rating: 'Upright', audience_score: 93, movie_details: 'http://www.rottentomatoes.com/m/good_will_hunting/', movie_reviews: 'http://www.rottentomatoes.com/m/good_will_hunting/reviews/?type=top_critics')
end